main: main.java.org.oinkcraft.antimobspam.AntiMobSpam
version: 1.5
api-version: 1.13
name: OinkAntiMobSpam
commands:
   AMSReload:
      description: Reloads plugin configuration
   AMSRadius:
      description: Gets player mob spawns within a 5 block radius
   AMSResetLog:
      description: Wipes clean log file